SPDX headers
iotaledger/iota.c pull request #101
Opened 2021-02-01 09:17 UTC by bernardoaraujor

# Description of change

adds SPDX identifier in source files
updates old years (`2019`, `2020`) to `2021`

solves #60 

## Type of change

- Bugfix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Documentation fix

## How the change has been tested

Visual inspection was done over files that didn't have SPDX headers.
`find` and `sed` were used to recursively replace `2019` and `2020` with `2021`.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests using CTest that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-02-01 09:57 UTC, oopsmonk requested changes
What I thought was adding missing the identifier in source files but keep files no change if the identifier has existed. changing all year strings seems like overkill. 
You can find files without the identifier in shell on Linux via `grep -Lr "// Copyright" src/*` and `grep -Lr "// Copyright" tests/*`

2021-02-01 16:26 UTC, bernardoaraujor commented
@oopsmonk cleaned up

2021-02-02 05:10 UTC, oopsmonk commented
> @oopsmonk cleaned up

10 files remain.
```
$ grep -Lr "// Copyright" src/*
src/core/models/payloads/milestone.h
src/core/models/inputs/utxo_input.c
src/core/models/inputs/utxo_input.h
src/core/models/outputs/sig_unlocked_single_output.c
src/core/models/outputs/sig_unlocked_single_output.h
src/core/utils/byte_buffer.c
src/core/utils/allocator.h
src/core/utils/byte_buffer.h
src/core/utils/iota_str.h
src/core/utils/iota_str.c
```

2021-02-02 13:38 UTC, bernardoaraujor commented
sorry @oopsmonk I should have used `grep` for self review.

2021-02-03 03:23 UTC, oopsmonk approved these changes
LGFM

2021-02-03 03:23 UTC, merged