Client - Get output address changes
iotaledger/iota.c pull request #167
Opened 2021-10-18 07:43 UTC by rebinmannady93

# Description of change

fixes #161
* Updated response object with ledgerIndex field.
* Support Bech32 address : /api​/v1​/addresses​/{bech32_addr}​/outputs
* Added few NULL and invalid address test cases

## Type of change
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

Passes local tests

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests using CTest that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-10-18 09:06 UTC, oopsmonk requested changes
please see my comment and sync with dev branch.

2021-10-18 09:06 UTC, oopsmonk commented on tests/client/api_v1/test_outputs_from_address.c
> +
`res` need to be freed before reusing it.

2021-10-19 05:19 UTC, rebinmannady93 commented on tests/client/api_v1/test_outputs_from_address.c
> +
Done.

2021-10-19 05:27 UTC, oopsmonk approved these changes

2021-10-19 05:28 UTC, merged