Core - Bump payload and essence types
iotaledger/iota.c pull request #371
Opened 2022-03-22 12:26 UTC by rebinmannady93

# Description of change

Fixes #352

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

test_get_message.c

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] My code follows the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests using CTest that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-03-22 13:19 UTC, matjazv approved these changes

2022-03-22 13:24 UTC, oopsmonk requested changes

2022-03-22 13:24 UTC, oopsmonk commented on src/core/models/message.h
> +  CORE_MESSAGE_PAYLOAD_MILESTONE = 1,
```suggestion
  CORE_MESSAGE_PAYLOAD_DEPRECATED = 0,
  CORE_MESSAGE_PAYLOAD_MILESTONE,
```

2022-03-23 01:57 UTC, rebinmannady93 commented on src/core/models/message.h
> +  CORE_MESSAGE_PAYLOAD_MILESTONE = 1,
Done.

2022-03-23 05:47 UTC, oopsmonk approved these changes

2022-03-24 06:12 UTC, merged