Wallet - implemented wallet_send_basic_outputs
iotaledger/iota.c pull request #389
Opened 2022-04-13 10:07 UTC by oopsmonk

# Description of change

- fixes #381 
- fixes #383 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

tested token transfer with a private Tangle

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [ ] My code follows the contribution guidelines for this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests using CTest that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-13 13:28 UTC, matjazv requested changes

2022-04-13 13:28 UTC, matjazv commented on src/core/models/outputs/byte_cost_config.c
> +                          uint8_t byte_factor_key) {
`config` could be NULL. Maybe a NULL check could be added.

2022-04-13 13:28 UTC, matjazv commented on src/wallet/wallet.c
> +      outputs_query_list_free(query_param);
`res_id` should also be freed.

```suggestion
      outputs_query_list_free(query_param);
      res_outputs_free(res_id);
```

2022-04-13 13:28 UTC, matjazv commented on src/wallet/wallet.c
> +int wallet_update_node_config(iota_wallet_t* w) {
`w` could be `NULL`. Maybe a `NULL` check could be added.

2022-04-13 13:28 UTC, matjazv commented on src/wallet/wallet.c
> +int wallet_send_basic_outputs(iota_wallet_t* w, bool change, uint32_t index, address_t* recv_addr, uint64_t send_amount,
`w` and `recv_addr` could be `NULL`. Maybe a `NULL` check could be added.

2022-04-13 13:28 UTC, matjazv commented on tests/wallet/test_wallet.c
> +#define FAUCET_IS_HTTPS 0
Should a `wallet` module also have a common `test_config.h` file? Or maybe whole library could have a common one?

2022-04-13 14:16 UTC, oopsmonk commented on tests/wallet/test_wallet.c
> +#define FAUCET_IS_HTTPS 0
yes, those configurations are temporary, we will have a common configuration and flags for online, local test scenarios with the node.

2022-04-13 18:50 UTC, matjazv approved these changes

2022-04-14 04:53 UTC, rebinmannady93 approved these changes

2022-04-14 05:42 UTC, merged