Doc - update crypto API documentation
iotaledger/iota.c pull request #390
Opened 2022-04-13 14:12 UTC by oopsmonk

# Description of change

fixes #372 

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Documentation fix

## How the change has been tested

passed exist tests

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests using CTest that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-04-13 14:36 UTC, matjazv requested changes

2022-04-13 14:36 UTC, matjazv commented on docs/api/crypto.md
> +The Cyppto APIs provide an abstraction layer of cryptography functions.
```suggestion
The Crypto APIs provide an abstraction layer of cryptography functions.
```

2022-04-13 18:48 UTC, matjazv approved these changes

2022-04-14 03:18 UTC, rebinmannady93 approved these changes

2022-04-14 05:43 UTC, merged