Core - Add Verification for Shimmer Coin and Its Bech32 HRP
iotaledger/iota.c pull request #398
Opened 2022-04-19 12:00 UTC by matjazv

# Description of change

- Fixed #386 
- Removed unneeded `IOTA_OUTPUT_ID_HEX_BYTES` define
- Made function `address_from_ed25519_pub` public

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

New unit tests are in  `tests/core/test_address.c`

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests using CTest that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-04-19 13:53 UTC, oopsmonk requested changes
please validate `atoi` and `rms` HRPs as well.

2022-04-19 17:09 UTC, matjazv commented
> please validate `atoi` and `rms` HRPs as well.

Thank you for the suggestion.
Unit tests for address validation for `atoi` and `rms` `HRP`s were added.

2022-04-20 02:41 UTC, rebinmannady93 approved these changes

2022-04-20 04:02 UTC, oopsmonk approved these changes

2022-04-20 04:04 UTC, merged