Tests - implemented fuctional tests
iotaledger/iota.c pull request #422
Opened 2022-05-06 08:30 UTC by oopsmonk

# Description of change

fixes #391, implemented functional-test application for interacting and testing with the network.

## Type of change

- Bugfix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

unit tests are passed in local

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests using CTest that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-06 13:18 UTC, matjazv requested changes
Functional tests bring nice addition to the library. Great work!

2022-05-06 13:18 UTC, matjazv commented on src/wallet/wallet.c
> +    coin_type = COIN_TYPE_IOTA;
Is in this case OK to set `coin_type` regarding a safety reasons? What if coins will be sent to an invalid network?

2022-05-06 13:18 UTC, matjazv commented on functional-tests/functional_cases.h
> +}test_state_e;
Some comments are missing because it's unclear what `NA` and `NG` means.

2022-05-06 13:18 UTC, matjazv commented on functional-tests/functional_cases.h
> +// Copyright 2022 IOTA Stiftung
In `functional_cases.h` some sections of the code like structs, enums, function definition don't have a comments.

2022-05-09 05:39 UTC, oopsmonk commented on src/wallet/wallet.c
> +    coin_type = COIN_TYPE_IOTA;
the bip44 coin type describes hierarchical deterministic wallets, it's not related to the network protocol. the wallet module is a general library for developers to create their own wallet applications and the coin type could be arbitrary.

2022-05-09 06:14 UTC, oopsmonk commented on functional-tests/functional_cases.h
> +}test_state_e;
aha, done. it's commonly used in manufacturing production.

2022-05-09 06:26 UTC, matjazv approved these changes

2022-05-09 08:53 UTC, rebinmannady93 approved these changes

2022-05-09 13:40 UTC, merged