Wallet - Create, Send and Destroy Alias Output
iotaledger/iota.c pull request #440
Opened 2022-05-18 13:51 UTC by matjazv

# Description of change

- fixed #436 
- fixed deserialization for `sender` and `issuer` feature blocks
- fixed `alias Id` deserialization for alias output
- fully implemented `json_output_deserialize` function 
- fixed alias output `metadata` length to `uint16_t`
- fixed `payload type` serialization for transaction essence 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

All local and tangle unit tests passed.

## Change checklist

Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests using CTest that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-05-19 08:25 UTC, oopsmonk requested changes
Nice work! :+1: 
some suggestions to improve user experience and leak issues.

2022-05-19 08:25 UTC, oopsmonk commented on src/wallet/output_alias.h
> +                             address_t* alias_addr, res_send_message_t* msg_res);
the wallet is able to derive the sender address and keypair from BIP44's path inside this method, it also reduces the coding which the user doesn't need to call `get_address_and_keypair`, like in the `examples/wallet/create_alias_output.c` 
maybe rename to `wallet_alias_output_create`?
```suggestion
int wallet_alias_create_send(iota_wallet_t* w, bool sender_change, uint32_t sender_index,
                             uint64_t const send_amount, address_t* state_ctrl_addr, address_t* govern_addr,
                             address_t* alias_addr, res_send_message_t* msg_res);
```

Please add a TODO comment about the optional Feature blocks. let's revisit it when needed.
```
// TODO: the alias output should be able to set optional feature blocks such as Sender/Metadata
```

2022-05-19 08:25 UTC, oopsmonk commented on src/wallet/output_alias.h
> +                                       res_send_message_t* msg_res);
the same as `wallet_alias_create_send`, the keypair and address are known by the wallet through the BIP44 path.
maybe rename to `wallet_alias_output_state_transition`?
```suggestion
int wallet_alias_state_transition_send(iota_wallet_t* w, byte_t alias_id[], bool state_ctrl_change, 
                                      uint32_t state_ctrl_index, address_t* govern_addr,
                                       res_send_message_t* msg_res);
```

2022-05-19 08:25 UTC, oopsmonk commented on src/wallet/output_alias.h
> +                              address_t* recv_addr, res_send_message_t* msg_res);
the same as `wallet_alias_create_send`, the keypair and address are known by the wallet through the BIP44 path.
maybe rename to `wallet_alias_output_destroy`?
```suggestion
int wallet_alias_destroy_send(iota_wallet_t* w, byte_t alias_id[], bool govern_change, uint32_t govern_index,
                              address_t* recv_addr, res_send_message_t* msg_res);
```

2022-05-19 08:25 UTC, oopsmonk commented on src/wallet/output_basic.h
> +                      uint64_t const send_amount, address_t* recv_addr, res_send_message_t* msg_res);
the same as `wallet_alias_create_send`, please revert this change.
fo consistancey, rename to `wallet_basic_output_send`?
```suggestion
int wallet_basic_send(iota_wallet_t* w, bool sender_change, uint32_t sender_index,
                      uint64_t const send_amount, address_t* recv_addr, res_send_message_t* msg_res);
```

2022-05-19 08:25 UTC, oopsmonk commented on src/wallet/output_alias.c
> +    goto end;
tx is not freed at the end.
```suggestion
   tx_payload_free(tx);
    ret = -1;
    goto end;
```

2022-05-19 08:25 UTC, oopsmonk commented on src/wallet/output_alias.c
> +    goto end;
message is not freed at the end.
```suggestion
    core_message_free(message);
    printf("[%s:%d] can not calculate transaction payload ID\n", __func__, __LINE__);
    goto end;
```

2022-05-19 08:25 UTC, oopsmonk commented on src/wallet/output_alias.c
> +int wallet_alias_create_send(iota_wallet_t* w, address_t* sender_addr, ed25519_keypair_t* sender_keypair,
please refactor this method to fix memory leak issues caused by transaction payload and message object.

2022-05-19 08:25 UTC, oopsmonk commented on src/wallet/output_alias.c
> +    ret = -1;
the same as `wallet_alias_create_send`, the `tx` memory will be owned by the message, but before message creation, the `tx` has not been freed here, also following exceptions.

2022-05-19 08:25 UTC, oopsmonk commented on src/wallet/output_alias.c
> +    ret = -1;
the same as `wallet_alias_create_send`

2022-05-19 08:25 UTC, oopsmonk commented on src/wallet/output_basic.c
> +    goto end;
the same as `wallet_alias_create_send`,

2022-05-19 10:46 UTC, matjazv commented on src/wallet/output_alias.h
> +                             address_t* alias_addr, res_send_message_t* msg_res);
Thank you for all code suggestions and improvements.

2022-05-19 15:27 UTC, oopsmonk approved these changes
lgtm

2022-05-19 15:27 UTC, oopsmonk commented on examples/wallet/send_basic_output.c
> +    "atoi1qpswqe4v8z2cdtgc7sfj0hfneqh37lhmjgnth36mfndwcxkjrakcvx42lsn";  // receiver address in bech32 format
it's not related to this PR but could you change this hard-coded bech32 address to the 2nd address index? so this example can work with different network configurations.

2022-05-19 16:02 UTC, matjazv commented on examples/wallet/send_basic_output.c
> +    "atoi1qpswqe4v8z2cdtgc7sfj0hfneqh37lhmjgnth36mfndwcxkjrakcvx42lsn";  // receiver address in bech32 format
This is a nice improvement. Tnx.
Done.

2022-05-20 05:32 UTC, rebinmannady93 approved these changes

2022-05-20 06:24 UTC, merged