erase seed on wallet_destroy
iotaledger/iota.c pull request #97
Opened 2021-01-27 16:01 UTC by bernardoaraujor

# Description of change

C applications can have a big attack surface, if not written properly.
Erasing seed from memory doesn't fully avoid potential exploits, but at least reduces attack surface and sets the bar a little higher.

solves #96 

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

```
/home/bernardo/develop/iota.c/build/tests/test_wallet_api
[validate_pib44_path:23] Err: invalid length of path
[wallet_create:205] Err: invalid parameters
[validate_pib44_path:23] Err: invalid length of path
[validate_pib44_path:56] Err: invalid path format: hardened is needed
[validate_pib44_path:65] Err: path format is m/44'/4218'/Account'/Change'
[validate_pib44_path:65] Err: path format is m/44'/4218'/Account'/Change'
[validate_pib44_path:65] Err: path format is m/44'/4218'/Account'/Change'
[validate_pib44_path:56] Err: invalid path format: hardened is needed
[validate_pib44_path:65] Err: path format is m/44'/4218'/Account'/Change'
515582FE648B0F10A2B2A1B91D7502190C979BAABFEE85B6BBB5020692E55D16
BC981BEA9924FE921CF41D7D8C5AE48FB453313FE4A6A1D6E88AC5AE42F0477A
6D9A35E98E2784A043D555E6B171C797B001C2A1495BC49BCE3BF0ABBDF73977
B177FCCC51153E638F6DD628A4A73F11A59408F3EA507F8A58A71FA16D2379A3
48E03225600898784B82DBD72DA1458BDBF63300E29A0203C268E55BF4D05E8F
/home/bernardo/develop/iota.c/tests/wallet/test_wallet.c:103:test_wallet_api:PASS

-----------------------
1 Tests 0 Failures 0 Ignored 
OK
```

I also wrote the following test, but `memcmp` breaks because I don't know how to properly handle dangling pointers:
```
void test_wallet_destroy() {
// create a wallet account
  iota_wallet_t* wallet = wallet_create(seed, "m/44'/4218'/0'/0'");
  TEST_ASSERT_NOT_NULL(wallet);

  byte_t *wallet_seed_addr = wallet->seed;
  wallet_destroy(wallet);

  byte_t null_seed[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
  TEST_ASSERT(memcmp(wallet_seed_addr, null_seed, IOTA_SEED_BYTES) == 0);
}
```

## Change checklist

- [x] My code follows the contribution guidelines for this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests using CTest that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-01-28 03:38 UTC, oopsmonk requested changes
First thing first, we know there are many ways to fetch security data from a system.
Can you elaborate on the situation or attack method in practice and how does this approach can prevent the attack based on your implementation?
so by that, you will not have the confusion about:
> I also wrote the following test, but memcmp crashes because I don't know how to properly handle dangling pointers

2021-01-30 23:07 UTC, bernardoaraujor commented
> Can you elaborate on the situation or attack method in practice and how does this approach can prevent the attack based on your implementation?

I imagine the following scenario:

Engineer writes application with buffer overflow vulnerability while also consuming `iota.c`.

He remembers to use `wallet_destroy()` appropriately, but the buffer overflow exposes memory that could still contain seed value.

Conclusion: there should never be a copy of a seed in memory (even if unallocated) without a corresponding wallet object.

By doing `sodium_memzero`, library users can trust that their seeds will never be exposed after `wallet_destroy()`.

cc @nothingismagick

2021-02-01 04:01 UTC, oopsmonk commented
> I imagine the following scenario:
> 
> Engineer writes application with buffer overflow vulnerability while also consuming `iota.c` (vulnerability unrelated from our lib).
> 
> He remembers to use `wallet_destroy()` appropriately, but the buffer overflow exposes memory that could still contain seed value.
> 
> Conclusion: there must never be a copy of a seed in memory (even if unallocated) without a corresponding wallet object.
> 
> By doing `sodium_memzero`, library users can trust that their seeds will never be exposed after `wallet_destroy()`.
> 
> cc @nothingismagick

1. buffer overflow is a malicious way to get root permission on an operating system. the attacker can access data in the system instead of memory. Is it possiable to get the seed from memory when the stack or heap is broken on wallet application?
2. sodium_memozero is an util provided by libsodium, it should not directly called in wallet API. 

I'm not saying erasing seed in memory is not a good idea but I'd like to know why and how can it help.

2021-02-01 15:17 UTC, bernardoaraujor commented
maybe buffer overflow isn't the best attack vector for this example (@nothingismagick would you know a better example?)
I'm just trying to imagine a scenario where wallet application memory is accessed even after deallocation.

2021-02-02 05:19 UTC, oopsmonk commented
> maybe buffer overflow isn't the best attack vector for this example (@nothingismagick would you know a better example?)

what is the exact problem this PR wants to solve? 

> I'm just trying to imagine a scenario where wallet application memory is accessed even after deallocation.

your test case has shown that you cannot access memory after deallocation. can you provide another case to prove this assumption?

2021-02-02 13:41 UTC, bernardoaraujor commented
ok @oopsmonk I see your point.

I still believe there could be some way to attack the seed, but I need to spend more time researching how to do this and prove why it's important to zero out seed on `wallet_destroy()` implementation.

Perhaps in the future I open a new PR with properly written justification and testing method.

2021-02-02 13:41 UTC, closed without merging